# Refer to: https://docs.influxdata.com/influxdb/v2/install/use-docker-compose/
services:
  # https://hub.docker.com/r/pgvector/pgvector
  pgvector-db:
    image: pgvector/pgvector:0.8.0-pg17
    # build:
    #   context: ./docker/postgres
    #   dockerfile: Dockerfile
    #   args:
    #     PG_MAJOR: ${PG_MAJOR}
    container_name: pgvector-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=aiagent
    ports:
      - "5432:5432"
    volumes:
      - pgvector-data:/var/lib/postgresql/data
      - ./docker/postgres/sqls/:/docker-entrypoint-initdb.d/

  qdrant:
    image: qdrant/qdrant:v1.13.6
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - qdrant-data:/qdrant/storage

volumes:
  pgvector-data:
  qdrant-data:

configs:
  qdrant_config:
    content: |
      log_level: INFO
