# Refer to: https://docs.influxdata.com/influxdb/v2/install/use-docker-compose/
services:
  db:
    # https://hub.docker.com/r/pgvector/pgvector
    image: pgvector/pgvector:0.8.0-pg17
    # build:
    #   context: ./docker/postgres
    #   dockerfile: Dockerfile
    #   args:
    #     PG_MAJOR: ${PG_MAJOR}
    container_name: pgvector-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=aiagent
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/sqls/:/docker-entrypoint-initdb.d/

volumes:
  pgdata:
